/*
 * Secret Server
 *
 * This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/gorilla/mux"
	"log"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"time"
)

type AddSecretParams struct {
	Secret string
	ExpireAfter string
	expireAfterViews  string
}

type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}


//func responseWriter(w http.ResponseWriter, r *http.Request, statusCode int, body interface{}) {
//
//}


func (sp *AddSecretParams) Validate() error {
	if strings.TrimSpace(sp.Secret) == "" {
		return errors.New("secret must not be empty")
	}
	re := regexp.MustCompile("^[1-9][0-9]*$")
	matched := re.Match([]byte(sp.expireAfterViews))
	if matched == false {
		return errors.New("expireAfterViews must be greater than 0")
	}
	re = regexp.MustCompile("^[0-9]*$")
	matched = re.Match([]byte(sp.ExpireAfter))
	if matched == false {
		return errors.New("expireAfter must be an integer, equals or grater 0")
	}
	return nil
}


func AddSecret(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	err := r.ParseForm()
	if err != nil {
		w.WriteHeader(http.StatusMethodNotAllowed) // 405 as swagger specified
		log.Println(err)
		return
	}
	p := r.Form
	sp := AddSecretParams{
		Secret: p.Get("secret"),
		expireAfterViews: p.Get("expireAfterViews"),
		ExpireAfter: p.Get("expireAfter"),
	}
	err = sp.Validate()
	if err != nil {
		w.WriteHeader(http.StatusMethodNotAllowed) // 405 as swagger specified
		fmt.Fprint(w, err)
		return
	}
	expAfter, _ := strconv.ParseInt (sp.ExpireAfter, 10, 64)
	expCount, _ := strconv.ParseInt (sp.expireAfterViews, 10, 32)
    createdAt   := time.Now()
	secret := Secret{
		SecretText:sp.Secret,
		RemainingViews:int32(expCount),
		ExpiresAt: createdAt.Add( time.Duration(expAfter) * time.Minute),
		CreatedAt: createdAt,
	}
	err = secret.encrypt()
	if err != nil {
		w.WriteHeader(http.StatusMethodNotAllowed) // 405 as swagger specified
		log.Println(err)
		return
	}
	err = secret.Save()
	if err != nil {
		w.WriteHeader(http.StatusMethodNotAllowed) // 405 as swagger specified
		log.Println(err)
		return
	}
	decrypted, err := secret.getDecryptedSecret()
	if err != nil {
		w.WriteHeader(http.StatusMethodNotAllowed) // 405 as swagger specified
		log.Println(err)
		return
	}
	secret.SecretText = decrypted
	j, _ := json.Marshal(secret)
	w.WriteHeader(http.StatusOK)
	_, err = fmt.Fprint(w, string(j))
	if err != nil {
		panic(err)
	}
}

func GetSecretByHash(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	vars := mux.Vars(r)
	hash, ok := vars["hash"]
	if !ok || len(hash) != 32 {
		w.WriteHeader(http.StatusNotFound) // 404 as swagger specified
		return
	}
	original := Secret{}
	err := LoadSecretFromDB(hash, &original)
	if err != nil{
		w.WriteHeader(http.StatusNotFound) // 404 as swagger specified
		log.Println(err)
		return
	}
	if original.Hash == "" {
		w.WriteHeader(http.StatusNotFound) // 404 as swagger specified
		return
	}
	response := original
	defer original.CountDown()
	decrypted, err := response.getDecryptedSecret()
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		panic(err)
		return
	}
	response.SecretText = decrypted
	j, _ := json.Marshal(response)
	w.WriteHeader(http.StatusOK)
	_, err = fmt.Fprint(w, string(j))
	if err != nil {
		panic(err)
	}
}
