version: '3'
services:
  goapi:
    image: olivernadj/secret-api-goapi:1.0.0
    ports:
      - "8080:8080"
    dns: 8.8.8.8
    restart: always
  prometheus:
    image: olivernadj/secret-api-prometheus:1.0.0
    ports:
      - "9090:9090"
    links:
      - goapi
    restart: always
  grafana:
    image: olivernadj/secret-api-grafana:1.0.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 5ecret
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: always
