apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: goapi
  name: goapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: goapi
    spec:
      containers:
      - image: olivernadj/secret-api-goapi:1.0.0
        name: goapi
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
