global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - '/etc/prometheus/prometheus.rules'
  - '/etc/prometheus/alerting.rules'

scrape_configs:
  - job_name: prometheus
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: secret_api
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "goapi:8080"
  - job_name: redis_exporter
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "redis-exporter:9121"