{
 "title": "API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "label_values(http_response_time_milliseconds_sum, service)"
   },
   {
    "name": "Handler",
    "query": "label_values(http_response_time_milliseconds_sum, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(http_response_time_milliseconds_sum{service=\"$Service\", handler=~\"$Handler\"}[1m])/ \navg_over_time(http_response_time_milliseconds_count{service=\"$Service\", handler=~\"$Handler\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_milliseconds_count{service=\"$Service\", handler=~\"$Handler\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Handler Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$Handler Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "repeat": "Handler",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(http_response_time_milliseconds_sum{service=\"$Service\", handler=\"$Handler\"}[1m])/ \navg_over_time(http_response_time_milliseconds_count{service=\"$Service\", handler=\"$Handler\"}[1m])\n* 1000) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "$Handler Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(http_response_time_milliseconds_sum{service=\"$Service\", handler=\"$Handler\"}[1m])/ \navg_over_time(http_response_time_milliseconds_count{service=\"$Service\", handler=\"$Handler\"}[1m])\n* 1000) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "$Handler Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(http_response_time_milliseconds_sum{service=\"$Service\", handler=\"$Handler\"}[1m])/ \navg_over_time(http_response_time_milliseconds_count{service=\"$Service\", handler=\"$Handler\"}[1m])\n* 1000) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Handler Latency Quantile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$Handler Latency Quantile",
   "type": "graph",
   "description": "The φ-quantile is the observation value that ranks at number φ*N among the N observations. Examples for φ-quantiles: The 0.5-quantile is known as the median. The 0.95-quantile is the 95th percentile.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "repeat": "Handler",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_time_milliseconds{service=\"$Service\", handler=~\"$Handler\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "$Handler Latency Quantile",
   "type": "graph",
   "description": "The φ-quantile is the observation value that ranks at number φ*N among the N observations. Examples for φ-quantiles: The 0.5-quantile is known as the median. The 0.95-quantile is the 95th percentile.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_time_milliseconds{service=\"$Service\", handler=~\"$Handler\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "$Handler Latency Quantile",
   "type": "graph",
   "description": "The φ-quantile is the observation value that ranks at number φ*N among the N observations. Examples for φ-quantiles: The 0.5-quantile is known as the median. The 0.95-quantile is the 95th percentile.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(http_response_time_milliseconds{service=\"$Service\", handler=~\"$Handler\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}